services:
  api:
    build: .
    depends_on:
      - mongo
      - redis

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    logging:
      driver: none
    networks:
      - auth-network

  mongo:
    command: mongod --quiet --logpath /dev/null 
    image: mongo:latest
    ports:
      - 27017:27017
    healthcheck:
      test: "exit 0"
    logging:
      driver: none
    networks:
      - auth-network

networks:
  auth-network:
    driver: bridge

